# Generated by Django 4.2.6 on 2023-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_slug_alter_women_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagWomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('slug', models.SlugField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='womens', to='women.tagwomen'),
        ),
    ]
