# Generated by Django 4.2.6 on 2023-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_tagwomen_women_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagwomen',
            options={'ordering': ['title'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='tagwomen',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
